### ISSUE TITLE
关于阻塞类代码请放入线程执行的问题

### ISSUE THREAD

**Issue by xuxiaoxia96** [fufuok/PyAgent#2]
轻量协程, 资源占用低, 若有阻塞类代码请放入线程执行
hi， fufuok，有个小问题
 这里我理解Python的线程模型是M:1模型，因此更适合IO密集的操作，通过协程调度。
但是关于后半句话，阻塞类代码放到线程执行。这里的线程是多线程吗，但是由于Python的GIL锁，是不是多线程也没法更好的解决阻塞的问题？只能多进程处理呢？
不知道我理解的对不对~希望可以帮忙答疑一下~

**Comment by fufuok** [comment]
对的, Python 使用事件循环驱动的协程实现并发, 一入协程, 所有协程, 不能有阻塞类代码. 比如不能用 `time.sleep()`, 事件循环维护着一个 ThreadPoolExecutor, 我们可以调用 run_in_executor 方法, 把可调用的对象发给它到线程时执行以实现非阻塞.

下面链接中 2 篇文章说得比较清楚, 可以参考:
https://cloud.tencent.com/developer/article/1591145

**Comment by xuxiaoxia96** [comment]
明白了！感谢解答
